kumuluzee:
  name: optimizator-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi-spec
    scan:
      packages: si.fri.rso.skupina1.optimizator.api.v1
    servers: http://localhost:8080/v1
    ui:
      mapping: /openapi
      server-auto-config:
        enabled: false
        original-uri-check: false
  health:
    checks:
      http-health-check:
        - connection-url: http://localhost:8080/v1/users
          type: readyness
        - connection-url: http://localhost:8080/openapi
          type: readyness
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="cdd0bbff-8f86-4910-ad4d-4ee50f6029b5-ls.logit.io"
                                  port="13921" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="all" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  rest-client:
    registrations:
      - class: geocoding-api
        url: https://forward-reverse-geocoding.p.rapidapi.com/v1
        read-timeout: 5000
integrations:
  uporabniki:
    baseurl: http://localhost:8081/graphql
  narocila:
    baseurl: http://localhost:8082/graphql
  geocoding:
    apiKey: ab28adb217msh37b289d5461b34ep1cbd51jsn55daa7d65546
    apiHost: forward-reverse-geocoding.p.rapidapi.com
rest-properties:
  maintenance-mode: false
  broken: false
